#pragma once

enum ExitCause {
    CAUSE_OK,
    CAUSE_NO_WORLD_FILE,
    CAUSE_INVALID_WORLD_INFO,
    CAUSE_INVALID_LINE_INFO,
    CAUSE_INVALID_LINE_CHARACTER,
    CAUSE_INVALID_WALL_INFO,
    CAUSE_INVALID_WALL_DIRECTION,
    CAUSE_INVALID_BEEPER_INFO,
    CAUSE_RESOURCE_DOES_NOT_EXIST
};